
@estherjwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjM0MzcxNDN9.XNqepUHm7GtuWLumBjwEhg7ieDfJYaTITwB2dNXz9EM
###
# Create User
post http://localhost:3000/user.json
Content-Type: application/json

{
  "name": "Esther",
  "password": "password"
}

###
#session create (login)
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "name":"Esther",
  "password": "password"
}

###

#Warehouse index:
get http://localhost:3000/warehouses.json
Content-Type: application/json

###

#Shipment create
post http://localhost:3000/shipments.json
Content-Type: application/json
Authorization: Bearer {{estherjwt}}

{
  "book_id": 3,
  "from_warehouse_id": "1",
  "to_warehouse_id": "2",
  "quantity": 0
}

###
get http://localhost:3000/shipments.json
Content-Type: application/json


###
patch http://localhost:3000/shipments/1
Content-Type: application/json
Authorization: Bearer {{estherjwt}}

{
  "book_id": 3,
  "from_warehouse_id": "1",
  "to_warehouse_id": "2",
  "quantity": 21
}

###

# get http://localhost:3000/shipments/86

###
#Inventory Show

get http://localhost:3000/inventory/:id
