
@estherjwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQ0NjgzNDN9.QS7Q_8z7e5Lm1BDIZyLi2_cj7AZKpn89lt6uxWyy40M
###
# Create User
post http://localhost:3000/user.json
Content-Type: application/json

{
  "name": "Esther",
  "password": "password"
}

###
#session create (login)
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "name":"Esther",
  "password": "password"
}

###

#Warehouse index:
get http://localhost:3000/warehouses.json
Content-Type: application/json

###

#Shipment create
post http://localhost:3000/shipments.json
Content-Type: application/json
Authorization: Bearer {{estherjwt}}

{
  "from_warehouse_id": "1",
  "to_warehouse_id": "2",
  "books": [{"book_id": 2, "quantity":1 },{"book_id": 1, "quantity":1 }],
  "shipment_id": 1
  }

###Shipment Index:
get http://localhost:3000/shipments.json
Content-Type: application/json


###shipment update:
patch http://localhost:3000/shipments/100
Content-Type: application/json
Authorization: Bearer {{estherjwt}}

{
  "books": [{"book_id": 2, "quantity":1 },{"book_id": 1, "quantity":1 }],
  "from_warehouse_id": "1",
  "to_warehouse_id": "2",
  "quantity": 21
}

###

# get http://localhost:3000/shipments/86

###
#Inventory Show

get http://localhost:3000/inventory/:id
